local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>ha", mark.add_file, { desc = "Add file" })
vim.keymap.set("n", "<leader>hm", ui.toggle_quick_menu, { desc = "Show quick menu" })

vim.keymap.set("n", "<leader>hh", function()
    ui.nav_file(1)
end, { desc = "Go to file 1" })
vim.keymap.set("n", "<leader>ht", function()
    ui.nav_file(2)
end, { desc = "Go to file 2" })
vim.keymap.set("n", "<leader>hn", function()
    ui.nav_file(3)
end, { desc = "Go to file 3" })
vim.keymap.set("n", "<leader>hs", function()
    ui.nav_file(4)
end, { desc = "Go to file 4" })
